# Mongoid Configuration
# =====================
#
# Copy this file to config/mongoid.yml and
# modify it accordingly. This file will automatically
# be copied to shared/config on the server when
# `cap deploy:setup` is ran the first time. Be sure
# to place production specific settings there

development:
  sessions:
    default:
      database: errbit_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: errbit_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

# set these environment variables on your prod server
production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      hosts:
        - "<%= ENV['MONGOID_HOST'] %>:<%= ENV['MONGOID_PORT'] %>"
  options:
    identity_map_enabled: true
